version: '3.7'
services:
  #service name
  web:
    # dockerfile location
    build: .
    ports:
      - '8000:8000'
  db:
    image: mysql:8.0.18
    ports:
      # HOST_PORT:CONTAINER_PORT
      - '3309:3306'
    volumes:
      - dbvolume:/var/lib/mysql
volumes:
  #volume name
  dbvolume: 